language: generic

env:
    global:
        - AWS_S3_BUCKET_NAME: "www.r3gui.com"
        # travis encrypt AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        #
        - secure: "NG3VXOyUa/TLjHrmnfLgtil8F4szJE32smOma2Mn/vGPTV8obZN5EYxDXsd1iTOWLulbm+nMg5MRQvf5+tJ9L7IIToHU3Qkes7FrHZdWe+eviuysF67UKmQlShXnY1O3L4hKWiJx9k7JnksoiNtH35VrAkWacJuBEVjzuYuJriy/OPtUJNNMzyJmlwYlOB6nTbO8K8V2TqbMsE0I373bD3UjWPhuD9ge2+9Y63ijqkdFQzZbJJFQXq/FYKn/+V0SUKVQl8KJfwjDNY8b3xYPUEzVCA2bKBHMcjpje5kd/zMIN/xk3wvJNzCD+fl2rwYYyT2hWdircvizEiw+BM1vi/XxtT0ofaazSL5ocS6eKsaJ4Kr6vWWUZXOaXIF3+9J3ShF6G5WvtvjgpGublWLv0iP4UkqTFaLyr8msJNble2kI66vKpPsBSxlp5vqp0+n+q2yZUIOA5p1YPQh1aoaCkeiQKL5ZGbe1aSrrUQ8a58Ei5DleE4WOS+qq7DRmUbrMachiqJZXhEUyw1DidbCIz9jdUWE/T+i1oCE1VNZGmzTE/17vv7jujDgRxQ7vWbuLgRZ8GKqdCYZT1Fja91NcUtGW1ylIbfZtqAsYKtZaO7MZfmQ/DNGwX33luRcajrZ8nn1dzGxvLB6SgtPZsCv84WwKD3vhqyPEwT3C7zr34t4="
    
        # travis encrypt AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        #
        - secure: "kAg9j/JmCI7HTmqT7WRCG1q+eWOvnnzS7DFEMaiayi8jfbJWAVCSU3IIWYYzOW0Jtx917QYbsF2IorZKciCh5i3KNNnBQqWjkSI1xPDtpfMIE36+fq1CEar2Sg5C+nm8Vz6ktPM1zYXp1b587KrsrMUQC8RC4QUEptVi0gidqT0yu4kROzKWtS+h+ZYbt4++Jd1SAHBbnQQDRND0VoczvSb9ZtJ2FiRcrTWtYjN60cFOKU95njqxCQyKCOhWeulru07I0X9yKywcYAXBI25ro6k2xVfa/gpP/nKcKc+t6F6vAHckpXaFc9ezP5WkqT2O79NV5PBNGmFb8xNNo+3ylZZ2GGxBAMEc2CS1DJlTqosJgFNts7nDpogCK+D9+OTgwlPtN8QQRTSmDyQt/xiK+UNF2HSXGHwXwK/iUl7qlMRBJncL0wtW6G7Jdjdw10rmVmVRPryEGh47wvbJNFXXo04q2X33CmfPxevirOJTCyJgXo/AaDySrDFYB9B1HpFQ9DXtKMyq3Lv0CWkEKLzoan/w2q0eeYwqfly2YAz8fwuEg9AZTaqrR/JJDyeexb1L4LsTrRMlHXadrkvFNjPo8quvYx2sekrK1MxyMvIu32UFczMS81+lFTe7EArxgyX+1FwsavZC6c+p442QDCAWlyhNc+DwlVcA3x6Y0DBCkLs="
       
addons:
  apt:
    packages:
      - poppler-utils
      - ghostscript

after_success: |
  wget https://dd498l1ilnrxu.cloudfront.net/travis-builds/0.4.40/r3-0c55141
  mv ./r3-0c55141 ./r3
  chmod +x ./r3
  wget https://raw.githubusercontent.com/gchiu/pharmac/master/scripts/grab-pdfs.reb
  ./r3 grab-pdfs.reb
  mkdir artifacts
  mv *.eps artifacts/
  mv *.png artifacts/
  # now move the artifacts to S3
  
deploy:
   provider: s3
   # these are set up in the global env
   access_key_id: $AWS_ACCESS_KEY_ID
   secret_access_key: $AWS_SECRET_ACCESS_KEY
   bucket: $AWS_S3_BUCKET_NAME
   skip_cleanup: true
   upload-dir: artifacts

