language: generic

global:
        # travis encrypt AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - secure: `A5CD5/LGjsJgD1xLINv1+PZ2UWWEVF8yaJP12Rleiq/Be/L5pOrvXHZY7ckQ1gteeZbl3B/vv30ZeBEiHBnm0e0yWSjbUPQ7XgwQcxv1plsOu6lqhppN3HcRApnoeoInQZt0z5rNVcYrtWw81NNWPiEgHUiJHSDlX3Vv/GmSgGg2HsRQm4rAgfbxvYDKtUd9zwq5opVtfbKNhFSQKMnVsC2ajwkZ0Yep/ktdrVtfQTAbfoerg+sfTMWaq4yhJKaldqwtPu3tGlJELhS5A3mjKVEy5sJF1RaRIO52vijJ92AxT5naJ3o+sXJwXDJbBca7YEY+DoulAiG1guw5kLKJvkpiiyjvaDgHFeKzn5+kt6wLOXDi0jRr4DqRkDGkZjgEhuqDiRV/Q6mesqJcLO+qgkSgAmm/YBZg4YFRs6adnszOFUhwSp0CS7raLCxEQXqeF4ft14NMytiTjfRuGnk4xtDs6c7POLjAl7FR0xSPVN1eU47hnM4IvCv6MKa2mJC5Kh1RxVr8ZaP3RDt6W/b/Bf9KQsPqYeAMbIBD4Rt3gykZvbQwvg67WsMQWO9gLSqTKGJWsleCwk1dmGKdVuZ/2xi2lnRMB9ldZNdP3FDK3rhMRrRMh3yDzZhxkV7zjPoP+2CgYhDKU8NFd8jPi/ROZSBxmtLkpAY5uAy+alLpZ1E=` 
        # travis encrypt AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        - secure: `QI3YDEgUQMTOaef9MB6eALduq4K+doTHHZEevtyAZOCr4XBcF3PhGw9M509DYcDDWA+y6pBg6eSCbcF3cdUMQnIDUIXanndTFVVbIjyMJWOkfxrFj2kHlWdNCGpLK/JDOx3T2zL2a3WBQxh4k4OUL9ZmvpKAFRdBbNR3jdLPRH+FifKoHs5IrmfQ3RtVzcEf8KJAZqO1D750ePg9NAHUHNTG9aAsRzHT7FXG5wcfXB7Knx9EdEoBbydx8rYEUg1prudx25U9SYvWMkd2r+1FLc1ihDJxinmA+YReP1uS+0G70xchDHeLWft3jZqniJK7bFwd+aYtAR6Q+jlVZMvDM76VrmPP39RpzB1hubabl1cJtKs4Rzz+kV2DLa3SipIZkR4/lCXu2Y6f93hdFDDC7Twzw/CYuM+f9nh7pEDlkgDLMlKnTs6uMhqknt/tc5B4AQL9QZJDTSlpe/+TkHNuh6B99Lz2OMpvhanQH3DZ34ETz350BccmuttGiw76v9scPA5OQn+tuUn/nFBPQJOwrqRKEpfaXFZuRCfb+FPc/MM2NgGnAIo6EbhtzqboXr8ICTk/u2qZleqGrPeaKVFevNTCRSIVdIA87QXvPLNDw5NZdNJ+HV1KBzDCHuWoHaKtn96zqcOZnYnjc/IJqGJ3ePsrGcLRfygMPAFtiJUnka8=`
        - AWS_S3_BUCKET_NAME: `www.r3gui.com`
       
deploy:
   provider: s3
   # these are set up in the global env
   access_key_id: $AWS_ACCESS_KEY_ID
   secret_access_key: $AWS_SECRET_ACCESS_KEY
   bucket: $AWS_S3_BUCKET_NAME
   skip_cleanup: true
   upload-dir: artifacts

addons:
  apt:
    packages:
      - poppler-utils
      - ghostscript

after_success: |
  wget https://dd498l1ilnrxu.cloudfront.net/travis-builds/0.4.40/r3-0c55141
  mv ./r3-0c55141 ./r3
  chmod +x ./r3
  wget https://raw.githubusercontent.com/gchiu/pharmac/master/scripts/grab-pdfs.reb
  ./r3 grab-pdfs.reb
  mkdir artifacts
  mv *.eps artifacts/
  mv *.png artifacts/
  # now move the artifacts to S3
