language: generic

global:
# travis encrypt AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
#
    - secure: `SIaanBcYBjG/R8n6tXGfSFvnT0UVGjUtF4u7zZLGHnKEo5zVmOXvTKJLOguNbrVntOfRAexCjE1Tr3wjZtg1gpdUiDE9AzntSuT7oMG2XiTgpFuQPjxl1AzBs36XH7f5RBVdkTNQDgHKb/OG7yvieb+00TzJPgEl4tLbdS8wApDZ8K07V9rvHRpqDolx8BS33Tbbpr75su8yyMo/aPHWO+GQwO0f4c1mFQWllNNL66vIP2aziES0yDrwWocsUSIgvmEkj7QvaudKvGo1AhijuVNtmdZH0UmOMuCHHdFchhH4xP72Hk+K+7d7WTO3y2ib9v99/070cVq95o0UywI8Eovr2g1z/4unAIGfKhXZkeecOS3whbAgEoTkYeUzxFrwxyet53Fzc9sMb/cOomxPduWYO3rhvtcvk4eo6E5CbB0/VCQGcJDl68ITt55PdFVEkOR887lhH2izG1YtU8YoeZkuhd5oD6HJslS0nfSnY3lopM1pMJGUe+4UeNlEizxz5xSZGTFYLHzkWw3HUsQGxM0v4h4UD76vne/3VgWXc2K13Dv1RXkTs35IlcW3ADh4sU4uFUQUEYiIi5TFwrWuvR/BQAHq/UM7TSaytpNcM7Xqtrg5tRoM5GpM8HC7YJVlMilZ2hbOlyptkXJYTTnI0104kdNBWevm5TvrhH9Uc3A=`

# travis encrypt AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
#
    - secure: `mes3E9GIDzgfRkm60MX1hIaRWbWEnkZdRLc98/Lgzay7Mw5VbmvdxUECwvV4v0znyJTBy8JDrHBSCjxBZeZEXfvhaCn0ntHVbXX73q6LKORlEumqTieJ0QsY4V9izu+ayN4bxZpN4DnJacjPASVLALmMqDWl6rq1MRv4bbJBDrPBaZWXQn/bHK5s5RGtz4FoIo8QVQ9r6XH3QanjzlYph5zhuxnPSIaWHd0uEepcpX/KqO7Fqfr6cN5zWBbijBWbLQGj8jngW8wv4oYDbyQfTbWo5409MTCbuGCNosR9vfmdYbO+LqilCWHJ/sQPNz/GBWcrA8knFklmkNa+IpkhlVC/po2jp+1olPzPh3aO2I2x8VhktEh4cpmzmODsJK2/0/HLUGweoydgtBTmPDGEuicO7yVmfMkHGoDT+q7kC1L5rxm4oO+YIRxcoAgNurnXIleKECTJnNBCl6/FHJ1wV/RoVvRry0XwNv4GHY3aKV4Yf43qzDI77mgH/BSpASTD3kK5jOdEHab9mTDZEcV0XZOk9feCCWtiDOVEdWSxzsm6LL6cAjIhUxxj9A1ZOw5+ben8ZjeMDYHPWKgu661xoTgRRsYv6NeJJqY/aKnsG2yIDJUDkLtf5hGPf2XOSlSbJ8Mq14IltezUHvAdc4Qicw6a7E5qg1RxAyJoutGwQq8=`
#
- AWS_S3_BUCKET_NAME: `www.r3gui.com`
       
deploy:
   provider: s3
   # these are set up in the global env
   access_key_id: $AWS_ACCESS_KEY_ID
   secret_access_key: $AWS_SECRET_ACCESS_KEY
   bucket: $AWS_S3_BUCKET_NAME
   skip_cleanup: true
   upload-dir: artifacts

addons:
  apt:
    packages:
      - poppler-utils
      - ghostscript

after_success: |
  wget https://dd498l1ilnrxu.cloudfront.net/travis-builds/0.4.40/r3-0c55141
  mv ./r3-0c55141 ./r3
  chmod +x ./r3
  wget https://raw.githubusercontent.com/gchiu/pharmac/master/scripts/grab-pdfs.reb
  ./r3 grab-pdfs.reb
  mkdir artifacts
  mv *.eps artifacts/
  mv *.png artifacts/
  # now move the artifacts to S3
