language: generic

env:
    global:
        - AWS_S3_BUCKET_NAME: "8th-dev"
        # travis encrypt AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        #
        - secure: "b/fMoOBPygs6b8AEyEcexHiYOg72alzQEzQ7fC10gwYw1ONTjwuX4+vLu50FaFm4Dwe+RAEVPn8931Z43eBM1E+gESICYznzLbaV/zsg8TisdlKbLe3td2UvH/mmkCBgEw6tEUPiH4p5GK1DJT12HJXmCTGOiUo4qYTHAllpDJOjr54x9tB3GEJhJmeK54/+VidEYyp9+PGeBP+e/b/JIV4cleXqQN+pb7cdHsVTIM5BRskP2LdNsoCG4oF31DJode/hg3xc2Tu6qKZ5EMIA6IO+kxn7pXiN2T1WV8lZ2l5CG7xnNej1s8E/opjE1Le1PgraeXiYLqYUBXbyAqSS01/nr65Ze0Uk8w3Y/WP0e7/AbEn21Z8oXwtEkdcjKw+o8idg6hwaFPz9sAe78Jj4bhVxTebxqJh5/5VO8ME/ac5Bw2zzGKKmBsToBqEd5GolNYmo70JTp1N2xn2rbIwtQbIFaKbJsXAIwaA4Dkp7VO/gOCF9z/m+S/Qszo1GX0978LVnUUDFxZMILWdmu2xohvvnAypnuEorw41zQfh9GN0hIbYzJSUpBaaE0JkK4CXhmPWjs15r2OpRw22eg8s93swhTUVyX++u2a0NfhbZuGvLrkRCwiFNjSlGQcuvQtkaleLGMrGDiQlAHKHW8Uhn+eBQwbK7GxNpIMlBDkjwwjU="
    
        # travis encrypt AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        #
        - secure: "D5HmHtW7D0UZ+RlsOHF6d3NdoP0CeL3qfQj+/3CWzV1kqt4tYB81dLPXFNVLB15KX3omTc6/62MwaulpcsMpjYJo2Vi37qP3AWSyoL0GSukHMY+N0zsblnEdKIo3EAi6wpR6Z0hB+Vjag8kzVjboP7TRSIcXI5NzuqgrRgTWKKyyPDP2YSWtQXFGRVBwh9t+uMgA7ljXEqSLmtw73JD9Jy4vM6UZX5Rfy8trsBvu8S/XuWWD6OPp2M2EyaS/W8zdXbTNdC0q4J7ZUga5twVFoviRkz3TEfCYlqNISZPZU1zaDnd7egNihFzw00apcpFDzAnrDaJ/6iwcd1BfiuMGj8mhdOIvxpO2/HFmj/U8Zf1WmyjxlmL4SFUhNR8i/anhUDs/xwGsW08d12f9zNXuJEbfGPE86SRoXXMJW5i+/DHIQ9BKGM571+KvVWI/4WGo41vSevYBJe6zTRO8fCKwqEwWfN5/1GSMZVtWRWOmoSp7Ghe8aUnsoA2N9V1Q4zaQjlB5Msl1781KEg8SKWsdaTpVRAY9xcBKbq4jZa9oCwISIdsR4lZUCSpAcRHSCYW5Er2utg7AnqVOfOrUOABGQpAjFIeLsRbPC4gI9yRnaJkwbZjzNlMLAf+524ViiZ9EXiriJ/L+yjG/MIuQZbXy5bFPYDlxuqjg01pl54dsEz0="

addons:
  apt:
    packages:
      - poppler-utils
      - ghostscript
      - rename

after_success:
  - wget https://dd498l1ilnrxu.cloudfront.net/travis-builds/0.4.40/r3-0c55141
  - mv ./r3-0c55141 ./r3
  - chmod +x ./r3
  - wget https://raw.githubusercontent.com/gchiu/pharmac/master/scripts/grab-pdfs.reb
  - ./r3 grab-pdfs.reb
  - ls
  # - mkdir artifacts
  - mv *.pdf images/
  - mv *.eps images/
  - mv *.png images/
  - ls images/
  # now move the images to S3
  
deploy:
   provider: s3
   # these are set up in the global env
   access_key_id: $AWS_ACCESS_KEY_ID
   secret_access_key: $AWS_SECRET_ACCESS_KEY
   bucket: $AWS_S3_BUCKET_NAME
   skip_cleanup: true
   upload_dir: images

