language: generic

env:
    global:
        - AWS_S3_BUCKET_NAME: "www.r3gui.com"
        # travis encrypt AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        #
        - secure: "P0sjPTC0X77Pzh/QbVymB6Ml6VA1PcilqZXTy4jxFIxwribbyenMlOXLnOS1bGPh/+oV8aqeRq+rXhZFBRElJWt8r8TgZcrnfbYA1rA/zD3JW9/Zu06ZZyyIwdTR+jofPRCbdsymegMuV0vFRRr29Zb/Evd0RajArnsb/a5RyRy0ZECQQvPrp4/OO9q63eUn9y0kDoifvYMz9KdRdFvjas9Mo64TqCaIebUF7NJhpBRQc1IvnbBxIFK01YXb7F1mrg31G5edOpeoCyULui8R0gTg1zIlMwrJ4VnQP2Z08h3+IHSmdgEsdw9OeGiucQHFmgpMMoblIus16JNuVbGOHXYJ7LfGG6J6N0dPRp/bY0ZWAT98ADQZ9xwamoc5duoP7KVr1nFB/3J3oj7F76uUn5iRkFgRW+kTUvC0DGfTQ9G9hF2rNHN4+S7gDR4/J0KgbsCR6ZxdS1+NTpR2Llde+l1RMHqqxtmWjwihAcZ6Pr8sEt+02l7kY9KaRuHmDPCtSX5+SaNM6FZpuSo9gdypDwUHOJsex6dcbLYRamdRHBszwXwY6UlmYijkcrQt/nj61VuAVTCnEBQsIVKX5lw7ZG8EXBy0T32Aeqb6how3UYCFzuRdEMQwE7VeiTJGYwiwbd9Nj1+nYI/mBsMiPatC2YWg3v5OO0hUjeE06btha8w="
    
        # travis encrypt AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        #
        - secure: "rPC+9Z8P3t3v5GSrVeD/L0elWk/6u5hONHgY9cTp8vYymhUT4b6Ez6+FjDkbKA4SCRvTZrzGwMZiOYV/kyQddd1E559aAC/6Xh8ey7dq11+aUEgjAVaXL88+WsNc+2QKvvu68ud5BCOcxSMvIgkZYdY3lN4iTnu0lkebIlHe0gIDSkV9gcKN2jxWjoJHYCDYJ1Xta8q49PkkNo92fJQN6Eu9kWpcqPUnvezc3l+W8W9P2dBgDPLzsExBKwwopfKrSH+Yz9ugRLdKCBMJUp33MQdt/R44yB0nGY0eBptwQE5va5gATX4SuaqI4McGOZkR+w9BIvXRGiuP9ejcoFWEklCSy3grqasZM/e0xyf3VJadirhFnVgLZY1/8DShsDSoruh+C+99ZII71mObd6EPJadcTJFF5GBGA1c3yGBXXga2tblZF9j66MyapdKRYVUXpH6w9739S1XD/xRii28PVuCdkebM8dBYEQhEIE0FLGjruw6b5BQ17LS4bkb5Zjx7eP9bTzecag5k+cgoAZhQXw/1uuoLOOmFSrVGQweoYzzXT6IWH1Dc4pAYYTQtux1TiP66F0sWZNTaFX57zuD/ez68HCMzIhd7z3ENJhlNZd6fmFgVGzR/2PMIGyJsOnPSl0Qwy3CS/+huDL5d2Izohbqg88ozsC0K4uUuAZTZYHs="
       
addons:
  apt:
    packages:
      - poppler-utils
      - ghostscript

after_success: |
  wget https://dd498l1ilnrxu.cloudfront.net/travis-builds/0.4.40/r3-0c55141
  mv ./r3-0c55141 ./r3
  chmod +x ./r3
  wget https://raw.githubusercontent.com/gchiu/pharmac/master/scripts/grab-pdfs.reb
  ./r3 grab-pdfs.reb
  mkdir artifacts
  mv *.eps artifacts/
  mv *.png artifacts/
  # now move the artifacts to S3
  
deploy:
   provider: s3
   # these are set up in the global env
   access_key_id: $AWS_ACCESS_KEY_ID
   secret_access_key: $AWS_SECRET_ACCESS_KEY
   bucket: $AWS_S3_BUCKET_NAME
   skip_cleanup: true
   upload-dir: artifacts

