language: generic

env:
    global:
    # travis encrypt AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    #
    - secure: "lPulRHoTx+Emt2mfOD1VLmhmGIC5XqSB8TIhCiVLkbWthwuMGX7oo5cuQUXiJMtrRD/qe8Th/426kzB4+ypk6BvoKLf6DAaEKawB3T1+B8ccQij3xHRI1cyEgdQn6eFpXZJZYa8bGDmtaYiB9eZjLabcZaJy/SQaHyUWVYmsRSiegQHTZjDeQWGzJWW+SUri62Ti+tDOibQIU26QnS371WRoEYVv74XXjgVL57yX0WAlaHF4il+rL73jNwV835IxUu9UFK8ROTPW7Cr78wvXdsdEwuJzEdfN+WzR/kVf2JFR+HS9fscIjIvMcbTTP+9b66LBgZ5SVcSQyeema6yHa3ovgzle1NuW08JgRyVSLZgEN+sQE/P/6SIa3EAS0I4zDV3MTa2EjVP3F4GzZdf6rOle3F8W0Dx5SY30P+sn62PIpcRnDFeFuWO4eGKR6kYNxp1SGXj35cerO/XeIg0G7v7uRLroaXmojvx8wkP6yGLlczDkOul+cbRlNDj3aAoIMvUtJQG1sKon8I74t0cWe+idTz9LD0b6zRi5G5R9Kx8XkA46OjTR6mCNEWo9gWp/M5G8vj0iHOcSdfLp4TzrdC0kqUiuud5R4xgtUjfITxms02XhIjEnF3o1q/0XMJBfWjhyiMxxRpmF9t7W9dUrlg0Y65NWlfQcw40I+yVnOMA="

    # travis encrypt AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    #
    - secure: "kAg9j/JmCI7HTmqT7WRCG1q+eWOvnnzS7DFEMaiayi8jfbJWAVCSU3IIWYYzOW0Jtx917QYbsF2IorZKciCh5i3KNNnBQqWjkSI1xPDtpfMIE36+fq1CEar2Sg5C+nm8Vz6ktPM1zYXp1b587KrsrMUQC8RC4QUEptVi0gidqT0yu4kROzKWtS+h+ZYbt4++Jd1SAHBbnQQDRND0VoczvSb9ZtJ2FiRcrTWtYjN60cFOKU95njqxCQyKCOhWeulru07I0X9yKywcYAXBI25ro6k2xVfa/gpP/nKcKc+t6F6vAHckpXaFc9ezP5WkqT2O79NV5PBNGmFb8xNNo+3ylZZ2GGxBAMEc2CS1DJlTqosJgFNts7nDpogCK+D9+OTgwlPtN8QQRTSmDyQt/xiK+UNF2HSXGHwXwK/iUl7qlMRBJncL0wtW6G7Jdjdw10rmVmVRPryEGh47wvbJNFXXo04q2X33CmfPxevirOJTCyJgXo/AaDySrDFYB9B1HpFQ9DXtKMyq3Lv0CWkEKLzoan/w2q0eeYwqfly2YAz8fwuEg9AZTaqrR/JJDyeexb1L4LsTrRMlHXadrkvFNjPo8quvYx2sekrK1MxyMvIu32UFczMS81+lFTe7EArxgyX+1FwsavZC6c+p442QDCAWlyhNc+DwlVcA3x6Y0DBCkLs="
    #
    - AWS_S3_BUCKET_NAME: "www.r3gui.com"
       
addons:
  apt:
    packages:
      - poppler-utils
      - ghostscript

after_success: |
  wget https://dd498l1ilnrxu.cloudfront.net/travis-builds/0.4.40/r3-0c55141
  mv ./r3-0c55141 ./r3
  chmod +x ./r3
  wget https://raw.githubusercontent.com/gchiu/pharmac/master/scripts/grab-pdfs.reb
  ./r3 grab-pdfs.reb
  mkdir artifacts
  mv *.eps artifacts/
  mv *.png artifacts/
  # now move the artifacts to S3
  
deploy:
   provider: s3
   # these are set up in the global env
   access_key_id: $AWS_ACCESS_KEY_ID
   secret_access_key: $AWS_SECRET_ACCESS_KEY
   bucket: $AWS_S3_BUCKET_NAME
   skip_cleanup: true
   upload-dir: artifacts

