language: generic

global:
# travis encrypt AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
#
- secure: `HY5IXxT1JYXuRcRZO3sT/3YroPX2U5qM5xYcWWVgV+wagLViCkwoXRIbBwGFpEP8KRUYmXyxUOWTXfcwM0lRDrlWu4aeUYZ+lbBora3gOULUv5NLAaRAqEjPp80zyq1ZPD8h1YeU4/S1CyD6r+/TqU89Oa9Z/R2r6tuCOSV2Mrn+LIe2v3ntz2dQvSKIIv9zSexIwkV/Gyh7uk4LvkgAu2jV3I7eeUHiiHgckZm4MLa9f14oKeaPu31mZXU5UwR+VhM3OoFyzQ20WT5TDgUylROF60/DJWhi902RLKTIOCNJTknng6ofhRyblTk/tq80wxCXkIWuwCHBpY2+IKfylMyTKF6H1dqy2FtjZFBoew+x4yHK/qouCEMro1PM4Ag4Qwn4COMyX1l33TAUe/fpApwBpBZZ6xrJhkRzXAB1wjJinZWczQ0otfFTaGGzCQvmTUP8bwvE4TJA22cK+lZRkOQyDkNcWdnAhljJJI2PxtKMuHnROp6TtznN24lsrZIBCoQztRY3Hpk8PJLm9Bsu4c6hG6aHvemWcUKabYp00zmbzFltOJ5S4/TlNOHukUrK0XpzMWJGhvExIB2PAIgFFSQyz7HfY/PDTaC8dDv8Ph1wsDhmQRtsyVQRZcMfzER/gvAFp/aR3Wx1mpGg5NLjV+u974018P8JAOlgrOEP5bM=`

# travis encrypt AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
#
- secure: `cjU6yEUgKzyCs57PgTPBRRPW7AtEy6Y0575wgEwHGydkNx4PQCTN9GYi7/WGUJR2vjjKvHhXjx8U8cQP9DSpGBUlSwv1QJuMvI22wiYY9RDR5XzNxjlSugP15e+4tCjx7zF9IcJw4EFX0SRSsxO+1wk2H/Rc7b51PEYXRdGeuN3wYyujGDoeF1OAtU4QG70/0osFHOu0J2nw4o97yIirbqzy3M/x9ketz4StOp2TVSQHqHAjMYMcyXQH61A2Uzd8b2q8EfHTFGBRb8r63JKyOKO3WsVdUh+ShLCY74mmrdErv/3Y+yonxyJ8Y/l6zrgbVRMoRsCURVz/dQvgDp6jnspmcpByA6n9kFYQwq9P/91QqmBh0RkI1WCRG7Xalb/Ze9oeW3BFGXiLrh7fRSDBOmweWKom+0wlc9EMtrFbBnpRzOaK77Ece6FE68VHTU8Y2BxAf9RTLZLsfcoopkfBCk0XkThdKT5aQMcpI9kfIpUKRfSjWBEBn6v99+O3y1Y+yxCMjcZ4jLcoq+A+/Q16Lp+Tfw+IMp3BtekfyxsVBNSAVXWHaA1lWu5oUQkLG7VzFfhHk9Y4qh7NHqIPtOv/OvHZ7sKihEoyljgp/hFiBbBcIzeci2u5h+i8VfykeQS7kWT9cMuBYo77H5CjeuLS0D4Sf6sp3vzhcOkF6cSurdo=`
#
- AWS_S3_BUCKET_NAME: `www.r3gui.com`
       
deploy:
   provider: s3
   # these are set up in the global env
   access_key_id: $AWS_ACCESS_KEY_ID
   secret_access_key: $AWS_SECRET_ACCESS_KEY
   bucket: $AWS_S3_BUCKET_NAME
   skip_cleanup: true
   upload-dir: artifacts

addons:
  apt:
    packages:
      - poppler-utils
      - ghostscript

after_success: |
  wget https://dd498l1ilnrxu.cloudfront.net/travis-builds/0.4.40/r3-0c55141
  mv ./r3-0c55141 ./r3
  chmod +x ./r3
  wget https://raw.githubusercontent.com/gchiu/pharmac/master/scripts/grab-pdfs.reb
  ./r3 grab-pdfs.reb
  mkdir artifacts
  mv *.eps artifacts/
  mv *.png artifacts/
  # now move the artifacts to S3
